// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cexanvnemkltpvaxcnmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleGFudm5lbWtsdHB2YXhjbm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTAzNzYsImV4cCI6MjA3MTg4NjM3Nn0.gx8JBe7BKLJKl2V33BdWHzVEu2XgrLajqts4oZa_2g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});